export const courses = [
  {
    courseName: 'Advanced Machine Learning',
    author: 'Alex Johnson',
    actualPrice: '₹1199',
    discountPercentage: '15%',
    tags: ['Machine Learning', 'Python'],
    saleEndDate: new Date('2024-01-12 22:00:00'),
  },
  {
    courseName: 'JavaScript Frameworks Masterclass',
    author: 'Emily White',
    actualPrice: '₹899',
    discountPercentage: '20%',
    tags: ['JavaScript', 'React', 'Vue'],
    saleEndDate: new Date('2024-01-15  11:00:00'),
  },
  {
    courseName: 'Full Stack Development with Django',
    author: 'Chris Turner',
    actualPrice: '₹1499',
    discountPercentage: '10%',
    tags: ['Python', 'Django', 'JavaScript'],
    saleEndDate: new Date('2024-01-16 11:00:00'),
  },
  {
    courseName: 'Cybersecurity Essentials',
    author: 'Sophia Davis',
    actualPrice: '₹1299',
    discountPercentage: '25%',
    tags: ['Cybersecurity', 'Network Security'],
    saleEndDate: new Date('2024-01-13  09:00:00'),
  },
  {
    courseName: 'Mobile App UX Design',
    author: 'Daniel Smith',
    actualPrice: '₹999',
    discountPercentage: '18%',
    tags: ['UX Design', 'Mobile App Development'],
    saleEndDate: new Date('2024-01-13  11:00:00'),
  },
  {
    courseName: 'Node.js for Beginners',
    author: 'Ava Williams',
    actualPrice: '₹699',
    discountPercentage: '22%',
    tags: ['Node.js', 'JavaScript'],
    saleEndDate: new Date('2024-01-13  10:00:00'),
  },
  {
    courseName: 'Artificial Intelligence in Business',
    author: 'Noah Turner',
    actualPrice: '₹1599',
    discountPercentage: '12%',
    tags: ['Artificial Intelligence', 'Business'],
    saleEndDate: new Date('2024-01-12  22:30:00'),
  },
  {
    courseName: 'Swift Programming for iOS',
    author: 'Emma Johnson',
    actualPrice: '₹1099',
    discountPercentage: '17%',
    tags: ['iOS', 'Swift'],
    saleEndDate: new Date('2024-01-13'),
  },
  {
    courseName: 'Responsive Web Design Principles',
    author: 'Liam White',
    actualPrice: '₹799',
    discountPercentage: '21%',
    tags: ['Web Design', 'HTML', 'CSS'],
    saleEndDate: new Date('2024-01-12  21:30:00'),
  },
  {
    courseName: 'Java Fundamentals',
    author: 'Olivia Turner',
    actualPrice: '₹899',
    discountPercentage: '0',
    tags: ['Java'],
  },
  {
    courseName: 'Game Development with Unity',
    author: 'Lucas Davis',
    actualPrice: '₹1399',
    discountPercentage: '14%',
    tags: ['Game Development', 'Unity'],
    saleEndDate: new Date('2024-01-12  21:30:00'),
  },
  {
    courseName: 'Python for Data Science',
    author: 'Aria Smith',
    actualPrice: '₹1199',
    discountPercentage: '0',
    tags: ['Python', 'Data Science'],
  },
  {
    courseName: 'Frontend Development Bootcamp',
    author: 'Mia Johnson',
    actualPrice: '₹999',
    discountPercentage: '18%',
    tags: ['HTML', 'CSS', 'JavaScript'],
    saleEndDate: new Date('2024-01-13  22:00:00'),
  },
  {
    courseName: 'C# Programming Mastery',
    author: 'Jackson White',
    actualPrice: '₹1099',
    discountPercentage: '0',
    tags: ['C#'],
  },
  {
    courseName: 'Angular Framework Deep Dive',
    author: 'Ava Turner',
    actualPrice: '₹1299',
    discountPercentage: '15%',
    tags: ['Angular'],
    saleEndDate: new Date('2024-01-13  11:00:00'),
  },
  {
    courseName: 'Data Visualization with D3.js',
    author: 'Ethan Davis',
    actualPrice: '₹899',
    discountPercentage: '0',
    tags: ['Data Visualization', 'D3.js'],
  },
  {
    courseName: 'Android App Development Basics',
    author: 'Isabella Smith',
    actualPrice: '₹799',
    discountPercentage: '0',
    tags: ['Android', 'Mobile App Development'],
  },
  {
    courseName: 'Vue.js for Frontend Development',
    author: 'Logan Johnson',
    actualPrice: '₹999',
    discountPercentage: '18%',
    tags: ['Vue.js', 'JavaScript'],
    saleEndDate: new Date('2024-01-14 11:00:00'),
  },
  {
    courseName: 'Cloud Computing Fundamentals',
    author: 'Sophie Turner',
    actualPrice: '₹1199',
    discountPercentage: '16%',
    tags: ['Cloud Computing'],
    saleEndDate: new Date('2024-01-12 22:00:00'),
  },
];
